### ISSUE TITLE
EKS Control Plane Implementation

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1787]
/kind feature

**Describe the solution you'd like**
Implement a new EKS control plane to help with the EKS implementation (#1534). This will handle the provisioning and management of a AWS EKS Cluster. Nodegroup support will be added via other issues.

It needs to support the following:
- EKS Cluster Creation
- EKS Cluster update
- EKS version update

**Anything else you would like to add:**
The parent tracking issue for full EKS support is #1534

### Tasks

- [x] IAM Roles Creation
- [x] IAM Roles Update (including trust profiles)
- [x] IAM Roles Deletion
- [x] EKS Cluster Creation
- [x] EKS Cluster Update (for example enabling logging)
- [x] EKS Cluster version update (this may be handled by the item above)
- [x] Security groups need investigating and scope updating
- [x] EKS Cluster Deletion
- [x] AWSManagedCluster Support
- [x] Kubeconfig creation
- [ ] Unit tests
- [ ] Start implementation of e2e tests
- [x] Tags only update to AWSManagedControlPlane (will use change from issue #1843)
