### ISSUE TITLE
Refactor the AWSManagedControlPlane out of the main controller

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1945]
/kind feature

**Describe the solution you'd like**
Split the AWSManagedControlPlane controller (and associated functionality) out from the main manager into a separate `eks control-plane` manager. This is so it can be optionally installed (instead of using feature gates) via clustectl and can have separate IAM permissions. 

**Anything else you would like to add:**
See this [discussion](https://kubernetes.slack.com/archives/C8TSNPY4T/p1599839490072800)

### Tasks:

- [x] skaffold the new control plane project
- [x] move existing code across to the new project
- [x] update existing documents
- [x] update makefile targets - bundling config
- [ ] change to clusterctl
