### ISSUE TITLE
Declarative way to delete AWS VPC CNI

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2287]
/kind feature
/area provider/eks
/priority important-soon
/help

**Describe the solution you'd like**
When provisioning a EKS cluster for Kubernetes v1.17 or less using CAPA where and i want to use a CNI that is different from the default Amazon VPC CNI (i.e something like Calico) i would like an easy way to ensure that the AWS VPC CNI is deleted.  For an unmanaged cluster (i.e. EC2/Kubeadm) this can be done using the **postKubeadmCommands** but this isn't available on the managed side. 

One potential way to do this is via a job that could be applied via a **ClusterResourceSet** or something like Flux2. And a longer-term solution may come in the way of the [machineadm bootstrapper poposal](https://github.com/kubernetes-sigs/cluster-api/pull/4221).

However, short term it would be good if we had a `disableVPVCNI` (or a name similar) that caused the AWS VPC CNI to be removed as part of the `AWSManagedControlPlane` reconciliation.

**Anything else you would like to add:**
This means deleting the `aws-node` daemonset from the `kube-system` namespace.

We would need to add some checks to the validating webhook that would error if the new flag was set AND the vpc cni addon was defined.

**Environment:**

- Cluster-api-provider-aws version: 0.6.4

**Tasks**

- [x] API Changes
- [x] Controller reconciliation changes
- [x] Record events for the deletion
- [x] Validation webhook check for VPC CNI and error
- [x] Validation webhook check for secondary CIDR and warn
- [x] Update docs
