### ISSUE TITLE
Umbrella: multi node control plane support

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#273]
/kind feature

Currently only a single control plane host is configured and deployable, but we should be able to deploy a full HA control plane (using colocated etcd and control plane).

- [x] Update deployed k8s version to v1.13 #412 
- [x] Add machine actuator support for control plane join #413
- [x] Document manual steps for creating an HA cluster using clusterctl phases #414
- [ ] Binary for automating HA cluster creation using clusterctl phases #415

/priority important-soon

**Comment by chuckha** [comment]
Upstream changes will have to take place since clusterctl does not support multiple control plane nodes yet.

https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/clusterdeployer/clusterdeployer.go#L421-L424

**Comment by ashish-amarnath** [comment]
Propose: renaming this issue to talk about a multi-node control plane. HA can mean cross region/az depending on the context that folks use it in.

**Comment by detiber** [comment]
@ashish-amarnath cross-region is out of scope here, since it is not supported by the AWS cloud provider.

**Comment by ncdc** [comment]
We'll want adequate time to test the pending PR (#528) and the v1alpha1 release is at the end of this week. Given that we have documentation on how to create a multi-node control plane, I'm comfortable deferring this until after the release.

/milestone Next

**Comment by ncdc** [comment]
What do you all think about closing this? It's currently possible to create a multi-node control plane with CAPA and v1alpha1. I would imagine any further work will go into the kubeadm bootstrapper and the TBD kubeadm control plane lifecycle manager.

**Comment by vincepri** [comment]
+1 on that, I checked and all the linked issues also seem to be closed

/close
