### ISSUE TITLE
UMBRELLA: Improved logging

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#330]
/kind feature

**Describe the solution you'd like**
Grouping a number of logging related issues together:

- [x] #305 - Refactor actuators around a context
- [x] #127 - Implement Events API
- [x] #324 - Mixed logging formats (glog vs. zap)
- [x] #259 - (Zap) Logs are extremely noisy
- [ ] #323 - Append context to logs

See also #78 on instrumentation and metrics

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
Given that logs are in a good shape and the last issue remaining in this umbrella is a nice to have, I'll go ahead and close this. Feel free to reopen if necessary.

/close
