### ISSUE TITLE
Update for vincepri

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#5082]
### GitHub handle

Remove vincepri

### Action

Remove

### Merge date

Owners already changed

### Reason for change

Vince moved himself to emeritus. Creating this to make sure we take the other actions.

### 🖱️Tasks

```[tasklist]
## Tasks to be done
- [ ] Update **cluster-api-aws-maintainers** section in [OWNER_ALIASES](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/OWNERS_ALIASES) in CAPA repo
- [ ] Create a PR with the change and add `/hold`
- [ ] Announce the change in the CAPA slack channel
- [ ] Add PSA in the notes doc for the next CAPA office hours
- [ ] After the lazy consensus review period remove the hold
- [ ] Update **cluster-api-provider-aws-maintainers** team in [this file](https://github.com/kubernetes/org/blob/main/config/kubernetes-sigs/sig-cluster-lifecycle/teams.yaml)
- [ ] Update **approvers** for CAPA jobs [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-aws/OWNERS)
- [ ] Update **approvers** from CAPA image promotion [here](https://github.com/kubernetes/k8s.io/blob/main/registry.k8s.io/images/k8s-staging-cluster-api-aws/OWNERS)
- [ ] Update **k8s-infra-staging-cluster-api-aws@kubernetes.io** [here](https://github.com/kubernetes/k8s.io/blob/main/groups/sig-cluster-lifecycle/groups.yaml)
- [ ] Update **sig-cluster-lifecycle-cluster-api-aws-alerts@kubernetes.io** [here](https://github.com/kubernetes/k8s.io/blob/main/groups/sig-cluster-lifecycle/groups.yaml)
```

**Comment by richardcase** [comment]
Create the PRs:

https://github.com/kubernetes/test-infra/pull/33565
https://github.com/kubernetes/org/pull/5191
https://github.com/kubernetes/k8s.io/pull/7354
https://github.com/kubernetes/k8s.io/pull/7355

**Comment by richardcase** [comment]
This was done. So:

/close
