### ISSUE TITLE
[v1alpha2] Forward ports needed

### ISSUE THREAD

**Issue by detiber** [kubernetes-sigs/cluster-api-provider-aws#913]
Some fixes/updates were added to release-0.3 that will need to be forward ported to master when it is more stable:

- [x] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/910 - cluster events (PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/961)
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/908 - LB fix (@chuckha)
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/839 - machine events (PR: #974) (@chuckha)
- [x] #916 - backoff & retry (PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/975) (@chuckha)
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/948 - clusterawsadm policy update (PR: #951)
- [x] https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/955 - Query VPC prior to deletion (PR: #973)

**Comment by chuckha** [comment]
Working on the first item, #910

**Comment by ncdc** [comment]
I've got 910 covered

**Comment by chuckha** [comment]
jk doing #908

**Comment by chuckha** [comment]
#908 needs no action.

It makes two changes:

1. It will update the load balancer on Update instead of Exists. The v1alpha2 code already exhibits this behavior: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/controller/awsmachine/awsmachine_controller.go#L268 This happens just after setting the provider id. This is the normal path of reconcile and there is no early-exit condition.

2. Always set the provider id. This is now always happening. in the `reconcileNormal` method: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/controller/awsmachine/awsmachine_controller.go#L250. This happens on every reconcile.

**Comment by chuckha** [comment]
@detiber Can you confirm my logic for #908 above?

If that's sound then this issue can be closed

**Comment by detiber** [comment]
@chuckha I agree it appears to be a noop given the new reconciliation behavior.
/close
