### ISSUE TITLE
Convert project to kubebuilder v2

### ISSUE THREAD

**Issue by chuckha** [kubernetes-sigs/cluster-api-provider-aws#989]
/kind feature

**Describe the solution you'd like**
A tracking issue for all the tasks needed to convert this to a kubebuilder v2 project to be in line with the other providers.

- [ ] #970 Convert makefile to be more kubebuilder-like
- [ ] #968 Convert conifg/ to be more kubebuilder-like
- [ ] #1004 Move cmd/manager/main.go to the top level
- [ ] #1005 Move api to expected place for kubebuilder generation to work seamlessly

**Comment by chuckha** [comment]
I'm going to see how much work is involved here and update the issues accordingly
